apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8sproj
  labels:
    app: myweb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myweb
  template:
    metadata:
      labels:
        app: myweb
    spec:
      containers:
      - name: k8sproj
        image: dullhuke/dullhuke
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: myweb
  name: k8spoj
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: myweb